### ISSUE TITLE
reliant on logstore_standard store

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/auth_bruteforce#2]
as your plugin relies on the logstore_standard store you should probably include a check somewhere to make sure the logstore_standard store is enabled and notify the admin that it will not work without it. Perhaps on the settings.php page?

**Comment by danmarsden** [comment]
... I forget auth still uses that nasty config.html file instead of normal settings.php - you might want to include it in the config.html page.

**Comment by danmarsden** [comment]
you may want to add details about this to your README as well, telling people how to enable the standard log store if required.

**Comment by eduardokraus** [comment]
I had not thought of that

**Comment by eduardokraus** [comment]
The plugin makes validation of Moodle version.

https://github.com/EduardoKrausME/auth_bruteforce/blob/master/auth.php#L27

**Comment by danmarsden** [comment]
all that line does it check the Moodle version. It does not check to see if the logstore_standard plugin is enabled.  you need to check something like:

get_config('tool_log', 'enabled_stores');

and make sure logstore_standard is enabled.

**Comment by danmarsden** [comment]
It would also be good to check if the logguests setting is required for the auth plugins to log failed login attempts as they will be coming from non-authenticated users.

**Comment by eduardokraus** [comment]
Access error as a visitor is the same.

**Comment by eduardokraus** [comment]
I just test
![Uploading Captura de Tela 2015-08-04 às 01.56.34.png…]()

**Comment by eduardokraus** [comment]
I just test
![captura de tela 2015-08-04 as 01 56 34](https://cloud.githubusercontent.com/assets/7725236/9053514/22328e14-3a4c-11e5-866b-b7a1170f0141.png)

**Comment by danmarsden** [comment]
Great to hear you're learning a lot... I just took another look and noticed that Petr improved the Brute force locking in core back in 2.5:
https://tracker.moodle.org/browse/MDL-21342
https://github.com/moodle/moodle/commit/b28247fe904d90530deef8ae6f51cc8772a89e62

This might mean that your custom plugin is no longer needed.

**Comment by eduardokraus** [comment]
I know.

Problem is that the IP is active and he can try forever and consuming server resources.

**Comment by eduardokraus** [comment]
Feature is disabled by default

**Comment by danmarsden** [comment]
yes on 2nd look your code does something slightly different but this is not clear from the description in your plugins db entry - you should improve the description to make it clear exactly how your plugin differs from the protection built-in to Moodle.

**Comment by eduardokraus** [comment]
This week I'll look at it fondly.

**Comment by eduardokraus** [comment]
mod_youtube will remake it

**Comment by eduardokraus** [comment]
And course_format_numeric?

**Comment by danmarsden** [comment]
I haven't looked at the other plugins yet but please review the comments on each plugin on moodle.org - some were missing the information required.

Also - you will need to add a check in your plugin for the logguests settting and warn users if this has been disabled - if it has been disabled then the user failed events will not be stored within the log_standard tables.
.
https://github.com/moodle/moodle/blob/803f565753bd9fe41acc802774adac75c2219880/admin/tool/log/store/legacy/classes/log/store.php#L218
